{% set name = "sqlitedict" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23a370416f4e1e962daa293382f3a8dbc4127e6a0abc06a5d4e58e6902f05d17

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - sqlitedict

about:
  home: https://github.com/RaRe-Technologies/sqlitedict
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.md
  summary: Persistent dict in Python, backed up by sqlite3 and pickle, multithread-safe.
  doc_url: https://github.com/RaRe-Technologies/sqlitedict
  dev_url: https://github.com/RaRe-Technologies/sqlitedict

extra:
  recipe-maintainers:
    - notestaff
    - synapticarbors
