travis:
  secure:
    BINSTAR_TOKEN: QBcTFfjm0nP0BkVNHOKE2WKATDxJAJMR5+Q+YR2hAhFOhzoI3QVZXdCW3mquNP1Y5EBbn4C7mkZlUi3t1h39N0oAsmWQNa7nw9pRnWYeQepixCzdxKUmf9hz25cmdCSVWGnAuLjLPriuHGNTWL0t6VB+CHjl8ZLrj1ZQnA2UieWxOTNH7bQ6M5X8eJWDiJpHGlD/kE2ZMkSRe3sMURGIeetMZVkFNAGWZFw9UFSJdXNq9UlqlSnFY0bb5poBBoMNuPnztrK+1EcpWtLoxcX4gN5Vz0SE6fQtrdBqmzvhYVPjVYKx3ui9zZyf0IA25k385GMABUdvshgRwn9UvOMqVyIi+bMD0P5KeLFzeYzVXxhd5K44RZYyU3TIM3FrW2AzeVCjxhAJGhkY51NPETgx3dDXct7ciEEktJNMd/t0R5PGtE87g/mAcJzQRb0musyNeHiwG3z45jRPsL+5CkcIcx33mx6uQxmprybdV7u2/kf6Pg9z4R5wVkkLVKyWsQdrOdrAe9UPHjSuhC/ZnehgSPis9SDh14drEh+7eTm6tX0DpTT1+aGXR/DPbPPPT9s8WIb31JcMvNeoD1Fr9Mt84kDZ937xdyiFHVEk9KFWe5PIYKWXPKmFQVvBM9FkAhKVeBipHM9i2Moo0erW1XW8e7RjCWJFmUfhbp7FEBcxI9k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
